server:
  AppVersion: 1.0.0
  Port: :5000
  Mode: Development
  JwtSecretKey: secretKey
  ReadTimeout: 5
  WriteTimeout: 5
  CtxDefaultTimeout: 12
  SSL: false
  Debug: false

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbName: go_store
  PostgresqlSslMode: false
  PgDriver: pgx


